documents:
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/01-Couverture.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/44_Introduction_MFT.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/45_Historique_certifications_CTN.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/47_regles_générales_certification_plongeurs_air.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/02_Generalites.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/03_Pack_decouverte_PE12.pdf'

  - url: 'http://www.ffessm.fr/gestionenligne/manuel/46_Qualification_PA12m.pdf'
    template: 'comic'
    la_overrides:
      9:
        char_margin: 0.3

  - url: 'http://www.ffessm.fr/gestionenligne/manuel/04_Plongeur_niveau_1.pdf'
    template: 'comic'
    la_overrides:
      10:
        char_margin: 0.3

  - url: 'http://www.ffessm.fr/gestionenligne/manuel/05_Qualification_PA20m.pdf'
    template: 'comic'
    la_overrides:
      9:
        char_margin: 0.3

  - url: 'http://www.ffessm.fr/gestionenligne/manuel/06_Plongeur_niveau_2.pdf'
    template: 'comic'
    la_overrides:
      14:
        char_margin: 0.3

  - url: 'http://www.ffessm.fr/gestionenligne/manuel/07_Qualification_PE40m.pdf'
    template: 'comic'
    la_overrides:
      10:
        char_margin: 0.3

  - url: 'http://www.ffessm.fr/gestionenligne/manuel/08_Qualification_PA40m.pdf'
    template: 'comic'
    la_overrides:
      10:
        char_margin: 0.3

  - url: 'http://www.ffessm.fr/gestionenligne/manuel/43_Qualification_PE60m.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/09_Plongeur_niveau_3.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/10_Guide_de_Palanquee_N4.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/11_Guide_palanquee_associe.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/12_Directeur_de_Plongee_N5.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/13_Initiateur.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/14_MF1.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/15_Tuteur_de_stage_initiateur.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/16_MF2.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/17_Moniteurs_associes.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/19_Passerelles_PADI_SSI.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/20_Nitrox.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/18_Intégration des plongeurs professionnels sécurité civil.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/21_Trimix.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/22_Recycleur.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/23_Recycleur_ferme_inspiration.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/48_Recycleur_ferme_submatix.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/24_RIFA_Plongee.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/25_ANTEOR.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/29_Randonnee_subaquatique.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/30_Jeunes.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/31_TIV.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/32_Station_de_gonflage.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/33_Vetement_etanche.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/49_sidemount_de_loisir.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/34_Code_du_sport_2012_mep_CTN.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/Guide_CTN_application_CdS_2012.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/36_Antidopage.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/37_Reglement_et_Charte_examens.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/40_plongée_Handisub.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/Charte_MF1.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/Charte_MF2.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/38_BPJEPS.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/39_DEJEPS.pdf'
  - url: 'http://www.ffessm.fr/gestionenligne/manuel/41_explorateur_6m_et_20m_UCPA.pdf'
